# Generated by Django 4.1.2 on 2022-10-14 08:38

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brand_company_country_project_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('uid', models.TextField(default=main.utils.uuid_generator, primary_key=True, serialize=False)),
                ('ru', models.CharField(max_length=250, verbose_name='Русский')),
                ('by', models.CharField(max_length=250, verbose_name='Белорусский')),
                ('ie', models.CharField(max_length=250, verbose_name='Ирландский')),
                ('eu', models.CharField(max_length=250, verbose_name='Европа')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
