# Generated by Django 4.1.2 on 2022-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_information_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='information',
            name='by',
            field=models.CharField(max_length=250, verbose_name='by site'),
        ),
        migrations.AlterField(
            model_name='information',
            name='eu',
            field=models.CharField(max_length=250, verbose_name='eu site'),
        ),
        migrations.AlterField(
            model_name='information',
            name='ie',
            field=models.CharField(max_length=250, verbose_name='ie site'),
        ),
        migrations.AlterField(
            model_name='information',
            name='ru',
            field=models.CharField(max_length=250, verbose_name='ru site'),
        ),
    ]
