# Generated by Django 4.1.2 on 2022-10-17 09:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_information_by_alter_information_eu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="country",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="country",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ru",
            field=models.CharField(max_length=250, null=True, verbose_name="Заголовок"),
        ),
    ]
