# Generated by Django 4.1.2 on 2022-10-20 12:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_equipment_item_alter_project_options_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="equip_images/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение оборудования",
                "verbose_name_plural": "Изображения оборудования",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Характеристика",
                    ),
                ),
                (
                    "numerical",
                    models.BooleanField(default=False, verbose_name="Числовое"),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OptionRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь характеристик",
                "verbose_name_plural": "Связи арактеристик",
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Значение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение характеристики",
                "verbose_name_plural": "Значения характеристики",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="equipment_item",
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="article",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Артикул"
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="country_create",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.country",
                verbose_name="Страна изготовителя",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="delivery_time",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Срок доставки"
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Высота (см)",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Длина (см)",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена поставщика (EUR)",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="supply_time",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Срок поставки"
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="warranty",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Гарантия"
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Вес (кг)",
            ),
        ),
        migrations.AddField(
            model_name="equipment_item",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ширина (см)",
            ),
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.AddField(
            model_name="optionrelation",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.equipment_item",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="optionrelation",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.option",
                verbose_name="Характеристика",
            ),
        ),
        migrations.AddField(
            model_name="optionrelation",
            name="option_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.optionvalue",
                verbose_name="Значение",
            ),
        ),
        migrations.AddField(
            model_name="equipment_image",
            name="equip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.equipment_item",
                verbose_name="Проект",
            ),
        ),
    ]
