# Generated by Django 4.1.2 on 2022-11-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_equipment_item_name_en_equipment_item_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="flag_en",
            field=models.BooleanField(default=False, verbose_name="Отображать на en"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="flag_ru",
            field=models.BooleanField(default=False, verbose_name="Отображать на ru"),
        ),
    ]
