# Generated by Django 4.1.2 on 2022-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_category_description_category_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="description_by",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO описание by"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_eu",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO описание eu"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ie",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO описание ie"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_kz",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO описание kz"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO описание ru"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_by",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO заголовок by"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_eu",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO заголовок eu"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ie",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO заголовок ie"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_kz",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO заголовок kz"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="SEO заголовок ru"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAINTENANCE", "Maintenance"),
                    ("REPAIR", "Repair"),
                    ("SELL", "Sell"),
                ],
                max_length=20,
                null=True,
                verbose_name="Вид работ",
            ),
        ),
    ]
