# Generated by Django 4.1.2 on 2022-11-01 13:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_category_description_remove_category_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="information",
            old_name="by",
            new_name="info_by",
        ),
        migrations.RenameField(
            model_name="information",
            old_name="eu",
            new_name="info_eu",
        ),
        migrations.RenameField(
            model_name="information",
            old_name="ie",
            new_name="info_ie",
        ),
        migrations.RenameField(
            model_name="information",
            old_name="ru",
            new_name="info_ru",
        ),
        migrations.AddField(
            model_name="information",
            name="info_kz",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="kz site"
            ),
        ),
    ]
