# Generated by Django 4.1.2 on 2022-11-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_rename_by_information_info_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("description", models.CharField(max_length=250, verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(default="no_image.jpg", upload_to="slider-index"),
                ),
            ],
        ),
    ]
