# Generated by Django 4.1.2 on 2022-11-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="description_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="slider",
            name="description_ru",
            field=models.CharField(max_length=250, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="slider",
            name="title_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="slider",
            name="title_ru",
            field=models.CharField(max_length=250, null=True, verbose_name="Заголовок"),
        ),
    ]
